/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited and should be in your git ignore file.
// It is auto-generated by Next.js — do not modify it.
