/**
 * XAI Global Product and Service Intelligence
 * Refreshed daily at 6AM, 12PM, 6PM Eastern
 * All data points labeled with evidence classification.
 * Private clickstream, competitor revenue, confidential ad budgets are NEVER invented.
 */

export type EvidenceLabel = 'VERIFIED' | 'ESTIMATED' | 'INFERRED' | 'UNAVAILABLE' | 'REQUIRES_VALIDATION'

export interface IntelligenceItem {
  rank: number
  name: string
  category: string
  subcategory: string
  search_demand: EvidenceLabel
  commercial_intent: EvidenceLabel
  market_growth: EvidenceLabel
  repeat_purchase: 'none' | 'low' | 'medium' | 'high'
  margin_potential: 'low' | 'medium' | 'high' | 'very_high'
  fulfillment_friction: 'low' | 'medium' | 'high'
  acquisition_scalability: 'low' | 'medium' | 'high'
  geographic_reach: 'local' | 'regional' | 'national' | 'global'
  roi_timeline_days: number
  notes: string
  last_refreshed: string
}

const R = '2026-07-23T17:00:00Z'

export const TOP_20_PRODUCTS: IntelligenceItem[] = [
  {rank:1,name:'AI Website Builder SaaS',category:'Software',subcategory:'AI Tools',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'global',roi_timeline_days:45,notes:'High recurring. AI-native moat possible.',last_refreshed:R},
  {rank:2,name:'Local Business Automation Toolkit',category:'Software',subcategory:'SMB Tools',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:60,notes:'SMBs seeking automation. Clear pain point.',last_refreshed:R},
  {rank:3,name:'Contractor Lead Generation Platform',category:'Software',subcategory:'Lead Gen',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Direct XPS/XAI alignment. First-party data advantage.',last_refreshed:R},
  {rank:4,name:'AI-Powered CRM for Contractors',category:'Software',subcategory:'CRM',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:60,notes:'Strong retention once embedded.',last_refreshed:R},
  {rank:5,name:'PWA Website Template Marketplace',category:'Digital Product',subcategory:'Templates',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'global',roi_timeline_days:30,notes:'One-time build, recurring sales.',last_refreshed:R},
  {rank:6,name:'AI Sales Script Generator',category:'Software',subcategory:'Sales Tools',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'global',roi_timeline_days:21,notes:'High-value, fast ROI. Subscription pricing.',last_refreshed:R},
  {rank:7,name:'Epoxy Flooring Estimate Calculator SaaS',category:'Software',subcategory:'Vertical SaaS',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:45,notes:'Deep vertical alignment with XPS.',last_refreshed:R},
  {rank:8,name:'Automated Review Collection System',category:'Software',subcategory:'Reputation',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Every local business needs this.',last_refreshed:R},
  {rank:9,name:'AI Proposal Generator for Contractors',category:'Software',subcategory:'Proposals',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Time savings directly measurable.',last_refreshed:R},
  {rank:10,name:'Digital Intake Form System',category:'Software',subcategory:'Forms',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'global',roi_timeline_days:21,notes:'PCU use case proven. White-label potential.',last_refreshed:R},
  {rank:11,name:'Floor Coating Visualizer App',category:'Software',subcategory:'Visualization',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'very_high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:90,notes:'Increases close rate for flooring contractors.',last_refreshed:R},
  {rank:12,name:'Contractor Website + SEO Package',category:'Software',subcategory:'Digital Marketing',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:45,notes:'Proven demand via PCU pipeline.',last_refreshed:R},
  {rank:13,name:'AI Social Proof Engine',category:'Software',subcategory:'Social',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'global',roi_timeline_days:45,notes:'Aggregates reviews, before/afters automatically.',last_refreshed:R},
  {rank:14,name:'Contractor Training Certification Platform',category:'Education',subcategory:'LMS',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:60,notes:'PCU model white-labelable.',last_refreshed:R},
  {rank:15,name:'Local SEO Dashboard',category:'Software',subcategory:'SEO',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:45,notes:'Every local business needs visibility.',last_refreshed:R},
  {rank:16,name:'Epoxy Product E-Commerce Store',category:'E-Commerce',subcategory:'Building Materials',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'medium',fulfillment_friction:'high',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:60,notes:'Inventory risk. Strong repeat purchase.',last_refreshed:R},
  {rank:17,name:'Booking and Scheduling SaaS for Contractors',category:'Software',subcategory:'Scheduling',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:45,notes:'Reduces no-shows, fills calendars.',last_refreshed:R},
  {rank:18,name:'Competitor Intelligence Dashboard',category:'Software',subcategory:'Market Intel',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:60,notes:'Powered by Xtreme Scraper.',last_refreshed:R},
  {rank:19,name:'AI Text + Email Follow-Up Automation',category:'Software',subcategory:'Marketing Automation',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Direct revenue attribution.',last_refreshed:R},
  {rank:20,name:'Job Costing and Margin Calculator',category:'Software',subcategory:'Financial Tools',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Contractors consistently underprice.',last_refreshed:R},
]

export const TOP_20_SERVICES: IntelligenceItem[] = [
  {rank:1,name:'Done-For-You Contractor Website Build',category:'Agency Service',subcategory:'Web Design',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:14,notes:'PCU pipeline proves demand.',last_refreshed:R},
  {rank:2,name:'Local SEO Management Retainer',category:'Agency Service',subcategory:'SEO',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:60,notes:'Recurring, measurable, automatable.',last_refreshed:R},
  {rank:3,name:'AI Automation Consulting',category:'Consulting',subcategory:'Process Automation',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:21,notes:'High hourly rate. Strategic value clear.',last_refreshed:R},
  {rank:4,name:'Google Ads Management for Contractors',category:'Agency Service',subcategory:'PPC',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:30,notes:'Direct revenue attribution.',last_refreshed:R},
  {rank:5,name:'Lead Generation as a Service',category:'Agency Service',subcategory:'Lead Gen',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'very_high',fulfillment_friction:'medium',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Xtreme Scraper powers fulfillment.',last_refreshed:R},
  {rank:6,name:'Brand Identity Development',category:'Creative Service',subcategory:'Branding',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:14,notes:'One-time high-ticket.',last_refreshed:R},
  {rank:7,name:'CRM Setup and Integration',category:'Technical Service',subcategory:'CRM',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:21,notes:'Upsell to monthly support.',last_refreshed:R},
  {rank:8,name:'Social Media Content Management',category:'Agency Service',subcategory:'Social Media',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'medium',fulfillment_friction:'high',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:45,notes:'Recurring but labor-intensive.',last_refreshed:R},
  {rank:9,name:'AI Chatbot Setup and Training',category:'Technical Service',subcategory:'AI',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:30,notes:'Monthly maintenance creates recurring revenue.',last_refreshed:R},
  {rank:10,name:'Email Automation Setup',category:'Technical Service',subcategory:'Email Marketing',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:21,notes:'Fast to deliver. Direct ROI measurable.',last_refreshed:R},
  {rank:11,name:'Reputation Management Service',category:'Agency Service',subcategory:'Reputation',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Automatable. High retention.',last_refreshed:R},
  {rank:12,name:'Funnel Design and Build',category:'Agency Service',subcategory:'Conversion',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:30,notes:'Measurable ROI through conversions.',last_refreshed:R},
  {rank:13,name:'Analytics and Reporting Setup',category:'Technical Service',subcategory:'Analytics',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:14,notes:'Upsell to monthly dashboard management.',last_refreshed:R},
  {rank:14,name:'Video Production for Contractors',category:'Creative Service',subcategory:'Video',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'high',fulfillment_friction:'high',acquisition_scalability:'low',geographic_reach:'regional',roi_timeline_days:30,notes:'Before/after videos are high-converting.',last_refreshed:R},
  {rank:15,name:'Google Business Profile Optimization',category:'Agency Service',subcategory:'Local SEO',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:14,notes:'Fast, high-demand, automatable at scale.',last_refreshed:R},
  {rank:16,name:'AI-Powered Lead Qualification Service',category:'Agency Service',subcategory:'Lead Gen',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'AI screens leads before human handoff.',last_refreshed:R},
  {rank:17,name:'Done-For-You Social Proof Collection',category:'Agency Service',subcategory:'Reputation',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'high',margin_potential:'high',fulfillment_friction:'low',acquisition_scalability:'high',geographic_reach:'national',roi_timeline_days:30,notes:'Automates review and testimonial collection.',last_refreshed:R},
  {rank:18,name:'Contractor Coaching and Strategy',category:'Consulting',subcategory:'Business Coaching',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'medium',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:14,notes:'PCU graduates are warm buyers.',last_refreshed:R},
  {rank:19,name:'Competitive Analysis and Market Positioning',category:'Consulting',subcategory:'Strategy',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'very_high',fulfillment_friction:'low',acquisition_scalability:'low',geographic_reach:'national',roi_timeline_days:14,notes:'Powered by Xtreme Scraper intelligence.',last_refreshed:R},
  {rank:20,name:'Technical SEO Audit and Fix',category:'Technical Service',subcategory:'SEO',search_demand:'INFERRED',commercial_intent:'INFERRED',market_growth:'INFERRED',repeat_purchase:'low',margin_potential:'high',fulfillment_friction:'medium',acquisition_scalability:'medium',geographic_reach:'national',roi_timeline_days:21,notes:'Upsell to monthly maintenance.',last_refreshed:R},
]

export function getTopOpportunities(type: 'product' | 'service', limit = 5): IntelligenceItem[] {
  const list = type === 'product' ? TOP_20_PRODUCTS : TOP_20_SERVICES
  return list
    .filter(i => i.roi_timeline_days <= 60 && i.margin_potential !== 'low')
    .sort((a, b) => a.roi_timeline_days - b.roi_timeline_days)
    .slice(0, limit)
}