import type { McpToolDefinition } from './types';

// XAB Canonical Tool Registry
// Source: XAB_XTREME_AUTO_BUILDER_COMPLETE_BASE44_HANDOFF_V2.xlsx — sheet 30_MCP_TOOL_REGISTRY
// 37 tools across 11 namespaces

export const XAB_TOOLS: McpToolDefinition[] = [
  // xab.control
  { id: 'T-001', namespace: 'xab.control', name: 'project.get', mode: 'read', purpose: 'Read scoped project state', risk: 'low', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { project_id: { type: 'string' } }, required: ['project_id'] }, outputSchema: { type: 'object' }, scopes: ['project:read'], timeoutMs: 5000 },
  { id: 'T-002', namespace: 'xab.control', name: 'project.create_draft', mode: 'draft', purpose: 'Create draft project', risk: 'medium', approval: 'none', receipt: 'yes', rollback: 'delete draft', inputSchema: { type: 'object', properties: { name: { type: 'string' }, source_ref: { type: 'string' } }, required: ['name'] }, outputSchema: { type: 'object' }, scopes: ['project:write'], timeoutMs: 10000 },
  { id: 'T-003', namespace: 'xab.control', name: 'workflow.start', mode: 'write', purpose: 'Start a permitted preview workflow', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'cancel workflow', inputSchema: { type: 'object', properties: { workflow_slug: { type: 'string' }, project_id: { type: 'string' } }, required: ['workflow_slug'] }, outputSchema: { type: 'object' }, scopes: ['workflow:run'], timeoutMs: 30000 },
  { id: 'T-004', namespace: 'xab.control', name: 'approval.request', mode: 'write', purpose: 'Create approval request for protected action', risk: 'high', approval: 'none', receipt: 'yes', rollback: 'expire request', inputSchema: { type: 'object', properties: { action: { type: 'string' }, scope: { type: 'object' }, risk: { type: 'string' } }, required: ['action', 'scope', 'risk'] }, outputSchema: { type: 'object' }, scopes: ['approval:request'], timeoutMs: 10000 },
  { id: 'T-005', namespace: 'xab.control', name: 'approval.decide', mode: 'protected', purpose: 'Operator approval decision', risk: 'critical', approval: 'operator', receipt: 'yes', rollback: 'superseding decision', inputSchema: { type: 'object', properties: { approval_id: { type: 'string' }, decision: { type: 'string', enum: ['approved', 'rejected'] }, rationale: { type: 'string' } }, required: ['approval_id', 'decision'] }, outputSchema: { type: 'object' }, scopes: ['approval:decide'], timeoutMs: 5000 },
  { id: 'T-006', namespace: 'xab.control', name: 'receipt.get', mode: 'read', purpose: 'Read receipt by ID', risk: 'low', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { receipt_id: { type: 'string' } }, required: ['receipt_id'] }, outputSchema: { type: 'object' }, scopes: ['receipt:read'], timeoutMs: 5000 },
  // xab.build
  { id: 'T-007', namespace: 'xab.build', name: 'repo.inspect', mode: 'read', purpose: 'Read XAB repository source truth', risk: 'low', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { path: { type: 'string' }, ref: { type: 'string' } } }, outputSchema: { type: 'object' }, scopes: ['repo:read'], timeoutMs: 10000 },
  { id: 'T-008', namespace: 'xab.build', name: 'branch.create', mode: 'write', purpose: 'Create feature branch in XAB', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'delete unmerged branch', inputSchema: { type: 'object', properties: { branch_name: { type: 'string' }, from_ref: { type: 'string', default: 'main' } }, required: ['branch_name'] }, outputSchema: { type: 'object' }, scopes: ['repo:write'], timeoutMs: 10000 },
  { id: 'T-009', namespace: 'xab.build', name: 'file.write_branch', mode: 'write', purpose: 'Write file to feature branch only', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'revert commit', inputSchema: { type: 'object', properties: { branch: { type: 'string' }, path: { type: 'string' }, content: { type: 'string' }, message: { type: 'string' } }, required: ['branch', 'path', 'content', 'message'] }, outputSchema: { type: 'object' }, scopes: ['repo:write'], timeoutMs: 15000 },
  { id: 'T-010', namespace: 'xab.build', name: 'pr.create_draft', mode: 'write', purpose: 'Create draft pull request', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'close PR', inputSchema: { type: 'object', properties: { title: { type: 'string' }, branch: { type: 'string' }, body: { type: 'string' } }, required: ['title', 'branch'] }, outputSchema: { type: 'object' }, scopes: ['repo:write'], timeoutMs: 10000 },
  { id: 'T-011', namespace: 'xab.build', name: 'preview.request', mode: 'write', purpose: 'Request Vercel preview deployment', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'remove preview', inputSchema: { type: 'object', properties: { branch: { type: 'string' }, project_id: { type: 'string' } }, required: ['branch'] }, outputSchema: { type: 'object' }, scopes: ['deploy:preview'], timeoutMs: 60000 },
  { id: 'T-012', namespace: 'xab.build', name: 'production.deploy', mode: 'protected', purpose: 'Production deploy — operator approval required', risk: 'critical', approval: 'operator', receipt: 'yes', rollback: 'deployment rollback', inputSchema: { type: 'object', properties: { commit_sha: { type: 'string' }, approval_id: { type: 'string' } }, required: ['commit_sha', 'approval_id'] }, outputSchema: { type: 'object' }, scopes: ['deploy:production'], timeoutMs: 120000 },
  // xab.data
  { id: 'T-013', namespace: 'xab.data', name: 'schema.inspect', mode: 'read', purpose: 'Inspect current Supabase schema', risk: 'medium', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { table: { type: 'string' } } }, outputSchema: { type: 'object' }, scopes: ['data:read'], timeoutMs: 10000 },
  { id: 'T-014', namespace: 'xab.data', name: 'migration.generate', mode: 'draft', purpose: 'Generate migration SQL file (draft only)', risk: 'high', approval: 'none', receipt: 'yes', rollback: 'discard file', inputSchema: { type: 'object', properties: { description: { type: 'string' }, tables: { type: 'array' } }, required: ['description'] }, outputSchema: { type: 'object' }, scopes: ['data:draft'], timeoutMs: 30000 },
  { id: 'T-015', namespace: 'xab.data', name: 'migration.apply_preview', mode: 'write', purpose: 'Apply migration to preview/staging only', risk: 'critical', approval: 'conditional', receipt: 'yes', rollback: 'down migration', inputSchema: { type: 'object', properties: { migration_file: { type: 'string' }, approval_id: { type: 'string' } }, required: ['migration_file', 'approval_id'] }, outputSchema: { type: 'object' }, scopes: ['data:migrate'], timeoutMs: 60000 },
  { id: 'T-016', namespace: 'xab.data', name: 'migration.apply_production', mode: 'protected', purpose: 'Apply migration to production — operator approval required', risk: 'critical', approval: 'operator', receipt: 'yes', rollback: 'verified rollback', inputSchema: { type: 'object', properties: { migration_file: { type: 'string' }, approval_id: { type: 'string' } }, required: ['migration_file', 'approval_id'] }, outputSchema: { type: 'object' }, scopes: ['data:migrate:production'], timeoutMs: 120000 },
  // xab.chat
  { id: 'T-017', namespace: 'xab.chat', name: 'room.create', mode: 'write', purpose: 'Create persistent chat room', risk: 'medium', approval: 'none', receipt: 'yes', rollback: 'archive room', inputSchema: { type: 'object', properties: { name: { type: 'string' }, project_id: { type: 'string' }, room_type: { type: 'string' } }, required: ['name'] }, outputSchema: { type: 'object' }, scopes: ['chat:write'], timeoutMs: 5000 },
  { id: 'T-018', namespace: 'xab.chat', name: 'message.publish', mode: 'write', purpose: 'Publish message to chat room', risk: 'medium', approval: 'none', receipt: 'yes', rollback: 'redaction event', inputSchema: { type: 'object', properties: { room_id: { type: 'string' }, content: { type: 'string' }, actor_type: { type: 'string' } }, required: ['room_id', 'content'] }, outputSchema: { type: 'object' }, scopes: ['chat:write'], timeoutMs: 5000 },
  { id: 'T-019', namespace: 'xab.chat', name: 'subscription.create', mode: 'write', purpose: 'Subscribe to pub/sub topic', risk: 'medium', approval: 'none', receipt: 'yes', rollback: 'delete subscription', inputSchema: { type: 'object', properties: { topic_id: { type: 'string' }, consumer: { type: 'string' } }, required: ['topic_id', 'consumer'] }, outputSchema: { type: 'object' }, scopes: ['chat:write'], timeoutMs: 5000 },
  { id: 'T-020', namespace: 'xab.chat', name: 'agent.pause', mode: 'protected', purpose: 'Pause agent in chat room', risk: 'high', approval: 'operator', receipt: 'yes', rollback: 'resume agent', inputSchema: { type: 'object', properties: { agent_id: { type: 'string' }, room_id: { type: 'string' }, reason: { type: 'string' } }, required: ['agent_id'] }, outputSchema: { type: 'object' }, scopes: ['chat:admin'], timeoutMs: 5000 },
  // xab.intel
  { id: 'T-021', namespace: 'xab.intel', name: 'source.register', mode: 'draft', purpose: 'Register public/licensed source and policy', risk: 'medium', approval: 'conditional', receipt: 'yes', rollback: 'disable source', inputSchema: { type: 'object', properties: { domain: { type: 'string' }, source_type: { type: 'string' }, license: { type: 'string' } }, required: ['domain'] }, outputSchema: { type: 'object' }, scopes: ['intel:source:write'], timeoutMs: 10000 },
  { id: 'T-022', namespace: 'xab.intel', name: 'crawl.dry_run', mode: 'read', purpose: 'Dry-run crawl policy check', risk: 'medium', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { url: { type: 'string' }, source_id: { type: 'string' } }, required: ['url'] }, outputSchema: { type: 'object' }, scopes: ['intel:policy'], timeoutMs: 15000 },
  { id: 'T-023', namespace: 'xab.intel', name: 'crawl.execute', mode: 'write', purpose: 'Execute policy-cleared crawl', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'cancel crawl', inputSchema: { type: 'object', properties: { source_id: { type: 'string' }, seed_url: { type: 'string' }, pages_budget: { type: 'number' } }, required: ['source_id', 'seed_url'] }, outputSchema: { type: 'object' }, scopes: ['intel:crawl'], timeoutMs: 120000 },
  { id: 'T-024', namespace: 'xab.intel', name: 'snapshot.get', mode: 'read', purpose: 'Read crawl snapshot', risk: 'low', approval: 'none', receipt: 'trace', rollback: 'n/a', inputSchema: { type: 'object', properties: { snapshot_id: { type: 'string' } }, required: ['snapshot_id'] }, outputSchema: { type: 'object' }, scopes: ['intel:read'], timeoutMs: 5000 },
  { id: 'T-025', namespace: 'xab.intel', name: 'rag.ingest', mode: 'write', purpose: 'Ingest content into RAG memory', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'delete derived chunks', inputSchema: { type: 'object', properties: { content: { type: 'string' }, source_id: { type: 'string' }, project_id: { type: 'string' } }, required: ['content'] }, outputSchema: { type: 'object' }, scopes: ['intel:rag:write'], timeoutMs: 60000 },
  // xab.finance
  { id: 'T-026', namespace: 'xab.finance', name: 'dataset.register', mode: 'draft', purpose: 'Register financial dataset', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'disable dataset', inputSchema: { type: 'object', properties: { name: { type: 'string' }, provider: { type: 'string' }, license: { type: 'string' } }, required: ['name', 'provider'] }, outputSchema: { type: 'object' }, scopes: ['finance:data:write'], timeoutMs: 10000 },
  { id: 'T-027', namespace: 'xab.finance', name: 'forecast.run', mode: 'write', purpose: 'Run probabilistic forecast', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'mark invalid', inputSchema: { type: 'object', properties: { model_id: { type: 'string' }, as_of: { type: 'string' }, horizon: { type: 'string' } }, required: ['model_id'] }, outputSchema: { type: 'object' }, scopes: ['finance:forecast'], timeoutMs: 300000 },
  { id: 'T-028', namespace: 'xab.finance', name: 'backtest.run', mode: 'write', purpose: 'Walk-forward backtest', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'mark invalid', inputSchema: { type: 'object', properties: { model_id: { type: 'string' }, windows: { type: 'array' } }, required: ['model_id'] }, outputSchema: { type: 'object' }, scopes: ['finance:model:write'], timeoutMs: 600000 },
  { id: 'T-029', namespace: 'xab.finance', name: 'model.validate', mode: 'write', purpose: 'Independent model validation', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'supersede review', inputSchema: { type: 'object', properties: { model_id: { type: 'string' }, validator_id: { type: 'string' } }, required: ['model_id'] }, outputSchema: { type: 'object' }, scopes: ['finance:validate'], timeoutMs: 300000 },
  { id: 'T-030', namespace: 'xab.finance', name: 'trade.execute', mode: 'blocked', purpose: 'BLOCKED — never in XAB scope', risk: 'blocked', approval: 'never', receipt: 'yes', rollback: 'n/a', inputSchema: { type: 'object' }, outputSchema: { type: 'object' }, scopes: [], timeoutMs: 0 },
  // xab.validation
  { id: 'T-031', namespace: 'xab.validation', name: 'suite.run', mode: 'write', purpose: 'Run validation suite', risk: 'medium', approval: 'conditional', receipt: 'yes', rollback: 'cancel run', inputSchema: { type: 'object', properties: { suite: { type: 'string' }, project_id: { type: 'string' }, environment: { type: 'string' } }, required: ['suite'] }, outputSchema: { type: 'object' }, scopes: ['validation:run'], timeoutMs: 300000 },
  { id: 'T-032', namespace: 'xab.validation', name: 'visual.capture', mode: 'write', purpose: 'Capture visual regression baseline', risk: 'medium', approval: 'conditional', receipt: 'yes', rollback: 'delete capture', inputSchema: { type: 'object', properties: { url: { type: 'string' }, project_id: { type: 'string' } }, required: ['url'] }, outputSchema: { type: 'object' }, scopes: ['validation:visual'], timeoutMs: 60000 },
  { id: 'T-033', namespace: 'xab.validation', name: 'repair.propose', mode: 'draft', purpose: 'Propose repair for failed test', risk: 'high', approval: 'none', receipt: 'yes', rollback: 'discard patch', inputSchema: { type: 'object', properties: { result_id: { type: 'string' }, defect: { type: 'string' } }, required: ['result_id', 'defect'] }, outputSchema: { type: 'object' }, scopes: ['validation:repair'], timeoutMs: 60000 },
  { id: 'T-034', namespace: 'xab.validation', name: 'repair.apply_branch', mode: 'write', purpose: 'Apply repair to feature branch', risk: 'high', approval: 'conditional', receipt: 'yes', rollback: 'revert commit', inputSchema: { type: 'object', properties: { repair_id: { type: 'string' }, branch: { type: 'string' } }, required: ['repair_id', 'branch'] }, outputSchema: { type: 'object' }, scopes: ['validation:repair:write'], timeoutMs: 60000 },
  // xab.release
  { id: 'T-035', namespace: 'xab.release', name: 'readiness.evaluate', mode: 'read', purpose: 'Evaluate release readiness scorecard', risk: 'high', approval: 'none', receipt: 'yes', rollback: 'n/a', inputSchema: { type: 'object', properties: { project_id: { type: 'string' } }, required: ['project_id'] }, outputSchema: { type: 'object' }, scopes: ['release:read'], timeoutMs: 30000 },
  { id: 'T-036', namespace: 'xab.release', name: 'rollback.request', mode: 'protected', purpose: 'Request production rollback', risk: 'critical', approval: 'operator', receipt: 'yes', rollback: 'roll-forward plan', inputSchema: { type: 'object', properties: { deployment_id: { type: 'string' }, reason: { type: 'string' }, approval_id: { type: 'string' } }, required: ['deployment_id', 'reason', 'approval_id'] }, outputSchema: { type: 'object' }, scopes: ['release:rollback'], timeoutMs: 120000 },
  { id: 'T-037', namespace: 'xab.release', name: 'production.release', mode: 'protected', purpose: 'Execute production release', risk: 'critical', approval: 'operator', receipt: 'yes', rollback: 'verified rollback', inputSchema: { type: 'object', properties: { commit_sha: { type: 'string' }, approval_id: { type: 'string' } }, required: ['commit_sha', 'approval_id'] }, outputSchema: { type: 'object' }, scopes: ['release:production'], timeoutMs: 120000 },
];

export function getTool(name: string): McpToolDefinition | undefined {
  return XAB_TOOLS.find(t => t.name === name);
}

export function getToolsByNamespace(ns: McpNamespace): McpToolDefinition[] {
  return XAB_TOOLS.filter(t => t.namespace === ns);
}

export function isBlocked(tool: McpToolDefinition): boolean {
  return tool.mode === 'blocked';
}

export function requiresOperatorApproval(tool: McpToolDefinition): boolean {
  return tool.approval === 'operator';
}
